{
 "title": "Service Manager General",
 "description": "Dashboard for Micrometer instrumented Service Manager (Spring Boot)\n\nFilter by datasource/namespace/node.",
 "tags": [
  "General",
  "SM",
  "Service Manager"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_memory_used_bytes {namespace=~\"$namespace\"},app)"
   },
   {
    "name": "pod",
    "label": "Podname",
    "query": "label_values({namespace=~\"$namespace\",app=~\"$application\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Info",
   "type": "text",
   "description": "Description of dashboard",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Service Manager Dashboard\n\n**Team**: SaaS  \n**Service**: Service Manager (Spring Boot)  \n**Aim**: Monitor application health, performance, and resource utilization to ensure smooth operation and quick issue resolution.\n\n---\n\n## **Key Metrics**\n- **CPU Usage**: Utilization and system load.\n- **HTTP Requests**: Count, status codes (2xx, 4xx, 5xx), and response times.\n- **JVM Metrics**: Heap/non-heap memory, garbage collection, and thread states.\n- **Logs**: Log event rates (info, debug, error).\n- **Buffers & Files**: Memory usage for buffers and open file descriptors.\n\n---\n\n## **Filters**\n- **Namespace**: Narrow down metrics for specific namespace."
   }
  },
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": " Actual Number of SM Pods",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 10, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Running state",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  max by (uid) (\n    kube_pod_info{\n      namespace=~\"$namespace\", \n      app=~\"$application\", \n      kubernetes_pod_name=~\"$pod\", \n      pod=~\"sf-service-manager-.*\"\n    }\n    * on (uid) group_left()\n    (\n      count by (uid) (\n        kube_pod_info{\n          namespace=~\"$namespace\", \n          app=~\"$application\", \n          kubernetes_pod_name=~\"$pod\", \n          pod=~\"sf-service-manager-.*\"\n        }\n      ) > 0\n    )\n    * on (uid) group_left()\n    (\n      process_uptime_seconds{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n      * on (namespace, pod, container) group_left(uid)\n      kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n      * on (namespace, pod) group_left(pod_ip)\n      kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n    )\n  ) > 0\n)\nor\n(\n  max by (uid) (\n    max_over_time(\n      kube_pod_info{\n        namespace=~\"$namespace\", \n        app=~\"$application\", \n        kubernetes_pod_name=~\"$pod\", \n        pod=~\"sf-service-manager-.*\"\n      }[5m]\n    )\n  ) * 0\n  unless\n  max by (uid) (\n    kube_pod_info{\n      namespace=~\"$namespace\", \n      app=~\"$application\", \n      kubernetes_pod_name=~\"$pod\", \n      pod=~\"sf-service-manager-.*\"\n    }\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"} * 1000\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Average CPU Usage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(system_cpu_usage{namespace=~\"$namespace\", pod=~\"$pod\"}[30s]) * 100\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average CPU Count (time range)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(system_cpu_usage{namespace=~\"$namespace\", pod=~\"$pod\"}[30s]) * 100\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(system_cpu_usage{namespace=~\"$namespace\", pod=~\"$pod\"}[30s]) * 100\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average CPU usage (time range)"
    }
   ]
  },
  {
   "title": "CPU Utilization per Pods",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(system_cpu_usage{namespace=~\"$namespace\", pod=~\"$pod\"}[30s]) * 100\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Average CPU Count",
   "type": "stat",
   "description": "This query measures the 1-minute system load average per pod, and enriches it with container and pod metadata (UID and IP). It helps identify overloaded pods and provides context for debugging and monitoring.",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      system_load_average_1m{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average CPU Count (time range)"
    }
   ]
  },
  {
   "title": "CPU Count vs System Load",
   "type": "timeseries",
   "description": "This query measures the 1-minute system load average per pod, and enriches it with container and pod metadata (UID and IP). It helps identify overloaded pods and provides context for debugging and monitoring.",
   "gridPos": { "h": 11, "w": 14, "x": 3, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "CPU Count [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "system_cpu_count{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "System Load [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      system_load_average_1m{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average CPU Count (time range)"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | type: {{level}}]"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average SM Memory Non-Heap",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})\n  )[${__range}:]\n)",
     "legendFormat": "Average CPU Count (time range)"
    }
   ]
  },
  {
   "title": "SM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})\n  )[${__range}:]\n)",
     "legendFormat": "average (time range)"
    }
   ]
  },
  {
   "title": "Average SM Memory Heap",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})\n  )[${__range}:]\n)",
     "legendFormat": "Average CPU Count (time range)"
    }
   ]
  },
  {
   "title": "SM Memory Heap",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})\n  )[${__range}:]\n)",
     "legendFormat": "average (time range)"
    }
   ]
  },
  {
   "title": "Average SM Memory Heap",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"})\n  )[${__range}:]\n)",
     "legendFormat": "Average CPU Count (time range)"
    }
   ]
  },
  {
   "title": "SM Memory Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 3, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"})\n  )[${__range}:]\n)",
     "legendFormat": "average used (time range)"
    }
   ]
  },
  {
   "title": "Heap && Non-Heap used",
   "type": "timeseries",
   "description": "1. **Non-Heap Memory Usage Percentage**: \n   Measures the percentage of used non-heap memory relative to the maximum allocated non-heap memory for sm pod  in specific namespace.\n\n\n2. **Heap Memory Usage Percentage**: \n   Measures the percentage of used heap memory relative to the maximum allocated heap memory for a sm pod in specific namespace.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"}) * 100 / sum(jvm_memory_max_bytes{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})\n",
     "legendFormat": "Non-Heap used"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
     "legendFormat": "Heap used"
    }
   ]
  },
  { "title": "HTTP Server Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Number of HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri!~\"/management/.*\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri!~\"/management/.*\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri!~\"/management/.*\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Rate per Second (ops/s)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Rate per Second (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "HTTP rate"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "HTTP average rate"
    }
   ]
  },
  {
   "title": "(2xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri!~\"/management/.*\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(4xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri!~\"/management/.*\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(5xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri!~\"/management/.*\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (without 5.x.x)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", status!~\"5..\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", status!~\"5..\"}[5m]))",
     "legendFormat": "HTTP avg response time"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", status!~\"5..\"})",
     "legendFormat": "HTTP max response time"
    }
   ]
  },
  {
   "title": "Average Max HTTP response time && Average HTTP response time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(http_server_requests_active_seconds_duration_sum{namespace=~\"$namespace\"}) \n    / \n    clamp_min(sum(http_server_requests_active_seconds_active_count{namespace=~\"$namespace\"}), 0.0001)\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max HTTP response time && Average HTTP response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds_max{namespace=~\"$namespace\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "Max HTTP request duration: [sm-pod-id: {{uid}} | method: {{method}}] "
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(http_server_requests_active_seconds_duration_sum{namespace=~\"$namespace\"}) \n    / \n    clamp_min(sum(http_server_requests_active_seconds_active_count{namespace=~\"$namespace\"}), 0.0001)\n  )[${__range}:]\n)",
     "legendFormat": "Average Active HTTP Request Duration (time range) "
    }
   ]
  },
  {
   "title": "50th && 95th && 99th percentile of HTTP response time",
   "type": "timeseries",
   "description": "Seconds",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_requests_seconds_bucket[5m])))\n",
     "legendFormat": "99th percentile of HTTP response time"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket[5m])))\n",
     "legendFormat": "95th percentile of HTTP response time"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_server_requests_seconds_bucket[5m])))\n",
     "legendFormat": "50th percentile of HTTP response time"
    }
   ]
  },
  { "title": "JVM Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Average Live Threads Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(jvm_threads_live_threads{namespace=~\"$namespace\", pod=~\"$pod\"})\n  )[${__range}:]\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(jvm_threads_live_threads{namespace=~\"$namespace\", pod=~\"$pod\"}[$__range])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(jvm_threads_live_threads{namespace=~\"$namespace\", pod=~\"$pod\"})\n  )[${__range}:]\n)\n",
     "legendFormat": "Average Live Threads (time range)"
    }
   ]
  },
  {
   "title": "SM Thread States",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, state) (\n  jvm_threads_states_threads{namespace=~\"$namespace\", app=~\"$application\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "open [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "process_files_max_files{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "max [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[$__range])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[1m])/rate(jvm_gc_pause_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[$__range])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[$__range])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "Allocated per pod [sm-pod-ip: {{instance}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[$__range])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Promoted per pod [sm-pod-ip: {{instance}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  { "title": "SM HikariPool-1 info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "Average connection acquisition time in HikariPool-1 last 5 min.",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(hikaricp_connections_acquire_seconds_sum{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])) \n/ \nsum(increase(hikaricp_connections_acquire_seconds_count{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average connection acquisition time in HikariPool-1 last 5 min.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(increase(hikaricp_connections_acquire_seconds_sum{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])) \n/ \nsum(increase(hikaricp_connections_acquire_seconds_count{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])))\n",
     "legendFormat": "Average connection acquisition time in HikariPool-1"
    }
   ]
  },
  {
   "title": "Ave. num. of active connections HikariPool-1",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n\n    )\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ave. num. of active connections HikariPool-1",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 3, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average number of active connections HikariPool-2 (time range)"
    }
   ]
  },
  {
   "title": "Ave. num. of active connections HikariPool-1",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total num. of active HikariPool-1 conn. last 5 min.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average of total number of active HikariPool-1 connection (time range)"
    }
   ]
  },
  {
   "title": "Ave. num.of pending connections HikariPool-1",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\"}[${__range}])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ave. num. of pending connections HikariPool-1",
   "type": "timeseries",
   "description": "requests waiting for a connection",
   "gridPos": { "h": 11, "w": 9, "x": 3, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\", pool=~\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg(\n  avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\"}[${__range}])\n)\n",
     "legendFormat": "Ave. num. of pending connections HikariPool-1"
    }
   ]
  },
  {
   "title": "Ave. num. of idle connections in the HikariPool-1",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ave. num. of idle connections in the HikariPool-1",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average number of idle connections in the HikariPool-1"
    }
   ]
  },
  { "title": "SM HikariPool-2 info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 } },
  {
   "title": "Ave. num. of active connections HikariPool-2",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average number of active connections HikariPool-2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average number of active connections HikariPool-2 (time range)"
    }
   ]
  },
  {
   "title": "Ave. num. of pending connections HikariPool-2",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total num. of active HikariPool-2 conn. last 5 min.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average of total number of active HikariPool-2 connection (time range)"
    }
   ]
  },
  {
   "title": "Ave. num. of pending connections HikariPool-2",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\"}[${__range}])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ave. num. of pending connections HikariPool-2",
   "type": "timeseries",
   "description": "requests waiting for a connection",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\", pool=~\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg(\n  avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\"}[${__range}])\n)\n",
     "legendFormat": "Ave. num. of pending connections HikariPool-2"
    }
   ]
  },
  {
   "title": "Ave. num. of idle connections HikariPool-2",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ave. num. of idle connections in the HikariPool-2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "Average number of idle connections in the HikariPool-2"
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 } },
  {
   "title": "Ave. num. of open connections in the Tomcat Server",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(tomcat_connections_current_connections{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ave. num. of open connections in the Tomcat Server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(tomcat_connections_current_connections{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(tomcat_connections_current_connections{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ave. num. of keep-alive connections in Tomcat",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(tomcat_connections_keepalive_current_connections{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ave. num. of keep-alive connections in Tomcat",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(tomcat_connections_keepalive_current_connections{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Max. num. of connections configured Tomcat Server",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(tomcat_connections_config_max_connections{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[${__range}])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max. num. of connections configured Tomcat Server",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 224 },
   "targets": [
    {
     "expr": "tomcat_connections_config_max_connections{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg(\n  avg_over_time(tomcat_connections_config_max_connections{namespace=~\"$namespace\", app=~\"$application\", kubernetes_pod_name=~\"$pod\"}[${__range}])\n)\n",
     "legendFormat": "Max. num. of connections configured Tomcat Server"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", id=\"direct\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "used [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", id=\"direct\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "capacity [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", id=\"direct\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "count [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", id=\"mapped\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "used [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", id=\"mapped\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "capacity [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$pod\", id=\"mapped\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "count [sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  }
 ]
}