{
 "title": "Service Manager HTTP",
 "description": "Dashboard for Micrometer instrumented Service Manager (Spring Boot)\n\nFilter by datasource/namespace/node.",
 "tags": [
  "SM",
  "Service Manager",
  "HTTP"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_memory_used_bytes {namespace=~\"$namespace\"},app)"
   },
   {
    "name": "podname",
    "label": "Podname",
    "query": "label_values({namespace=~\"$namespace\",app=~\"$application\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Info",
   "type": "text",
   "description": "Description of dashboard",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Service Manager HTTP Dashboard\n\nTeam: SaaS  \nService: Service Manager (Spring Boot)  \nAim: Monitor HTTP request metrics, response times, and server performance to ensure optimal API performance and reliability.\n\n---\n\n## Key Metrics\n- HTTP Requests: Total requests, status codes (2xx, 4xx, 5xx), and rates per second.\n- Response Times: Average, 95th, and 99th percentile response times.\n- Tomcat Metrics: Active threads, idle threads, and connection counts.\n- Endpoint-Specific Metrics: Breakdown for /api/v1/service (POST, PATCH, DELETE).\n\n---\n\n## Filters\n- Namespace, Application, Pod Name: Narrow down metrics for specific instances."
   }
  },
  { "title": "HTTP General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Number of HTTP requests per second (all endpoints)",
   "type": "stat",
   "description": "requests/s",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th && 95th percentile of HTTP response time",
   "type": "timeseries",
   "description": "seconds",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (le))",
     "legendFormat": "95th percentile of HTTP response time"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (le))",
     "legendFormat": "99th percentile of HTTP response time"
    }
   ]
  },
  {
   "title": " Actual Number of SM Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All endpoints without /management/*",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Number of HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri!~\"/management/.*\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri!~\"/management/.*\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri!~\"/management/.*\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP Rate per Second (without /management/.*)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", uri!~\"/management/.*\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Rate per Second (without /management/.*)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri!~\"/management/.*\"}[5m]))",
     "legendFormat": "HTTP Rate All"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri!~\"/management/.*\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "HTTP Average Rate All"
    }
   ]
  },
  {
   "title": "(2xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri!~\"/management/.*\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(4xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri!~\"/management/.*\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(5xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri!~\"/management/.*\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (without 5.x.x) (without /management/.*)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri!~\"/management/.*\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri!~\"/management/.*\"}[5m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri!~\"/management/.*\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Average Max HTTP response time && Average HTTP response time",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(http_server_requests_active_seconds_duration_sum{namespace=~\"$namespace\"}) \n    / \n    clamp_min(sum(http_server_requests_active_seconds_active_count{namespace=~\"$namespace\"}), 0.0001)\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max HTTP response time && Average HTTP response time (without /management/.*)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds_max{namespace=~\"$namespace\", uri!~\"/management/.*\"}\n* on (namespace, pod) group_left(uid)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$podname\"}",
     "legendFormat": "Max HTTP request duration: sm-pod-id: {{uid}} method: {{method}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(http_server_requests_active_seconds_duration_sum{namespace=~\"$namespace\", uri!~\"/management/.*\"}) \n    / \n    clamp_min(sum(http_server_requests_active_seconds_active_count{namespace=~\"$namespace\", uri!~\"/management/.*\"}), 0.0001)\n  )[${__range}:]\n)",
     "legendFormat": "Average Active HTTP Request Duration (time range) "
    }
   ]
  },
  {
   "title": "/api/v1/service/* - POST (CREATE)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Number of HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=\"/api/v1/service\", method=\"POST\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri=\"/api/v1/service\", method=\"POST\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri=\"/api/v1/service\", method=\"POST\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri=\"/api/v1/service\", method=\"POST\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP CREATE Rate per Second",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri=\"/api/v1/service\", method=\"POST\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP CREATE Rate per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri=\"/api/v1/service\", method=\"POST\"}[5m]))",
     "legendFormat": "HTTP CREATE"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri=\"/api/v1/service\", method=\"POST\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "Average HTTP CREATE Rate per Second"
    }
   ]
  },
  {
   "title": "HTTP CREATE Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\",  uri=\"/api/v1/service\", method=\"POST\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=\"/api/v1/service\", method=\"POST\"}[5m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=\"/api/v1/service\", method=\"POST\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "(2xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri=\"/api/v1/service\", method=\"POST\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=\"/api/v1/service\", method=\"POST\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(4xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri=\"/api/v1/service\", method=\"POST\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=\"/api/v1/service\", method=\"POST\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(5xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri=\"/api/v1/service\", method=\"POST\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=\"/api/v1/service\", method=\"POST\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/api/v1/service/* - PATCH (UPDATE)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }
  },
  {
   "title": "Number of HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP CREATE Rate per Second",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 10, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP PATCH Rate per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[5m]))",
     "legendFormat": "HTTP PATCH"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "Average HTTP PATCH Rate per Second"
    }
   ]
  },
  {
   "title": "HTTP PATCH Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[5m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "(2xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(4xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(5xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=~\"/api/v1/service/.*\", method=\"PATCH\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "/api/v1/service/* - DELETE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Number of HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP DELETE Rate per Second",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 10, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP DELETE Rate per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[5m]))",
     "legendFormat": "HTTP"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[5m]))\n  )[${__range}:]\n)",
     "legendFormat": "Average HTTP DELETE Rate per Second"
    }
   ]
  },
  {
   "title": "HTTP DELETE Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[5m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\", status!~\"5..\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "(2xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"2.*\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(4xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"4.*\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(5xx status) Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", status=~\"5.*\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range])) \n  / \n  sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\", uri=~\"/api/v1/service/.*\", method=\"DELETE\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Max. num. of connections configured Tomcat Server",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(tomcat_connections_config_max_connections{namespace=~\"$namespace\", app=~\"$application\"}[${__range}])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max. num. of connections configured Tomcat Server",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 81 },
   "targets": [
    {
     "expr": "tomcat_connections_config_max_connections{namespace=~\"$namespace\", app=~\"$application\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    },
    {
     "expr": "avg(\n  avg_over_time(tomcat_connections_config_max_connections{namespace=~\"$namespace\", app=~\"$application\"}[${__range}])\n)\n",
     "legendFormat": "Max. num. of connections configured Tomcat Server"
    }
   ]
  },
  {
   "title": "Current open connections in Tomcat",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(tomcat_connections_keepalive_current_connections{namespace=\"$namespace\", application=~\"$application\", pod=~\"$podname\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=\"$namespace\", pod=~\"$podname\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=\"$namespace\", pod=~\"$podname\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Num. of active threads processing requests in Tomcat",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(tomcat_threads_busy_threads{namespace=\"$namespace\", application=~\"$application\", pod=~\"$podname\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=\"$namespace\", pod=~\"$podname\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=\"$namespace\", pod=~\"$podname\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Num. of idle threads in Tomcat",
   "type": "timeseries",
   "description": "count",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(tomcat_threads_config_max_threads{namespace=\"$namespace\", application=~\"$application\", pod=~\"$podname\"}[1m]) \n  - \n  avg_over_time(tomcat_threads_busy_threads{namespace=\"$namespace\", application=~\"$application\", pod=~\"$podname\"}[1m])\n)\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=\"$namespace\", pod=~\"$podname\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=\"$namespace\", pod=~\"$podname\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  { "title": "PGW - GENERAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Number of Executed Requests during selected time",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pgw_response_time_seconds_count{namespace=~\"$namespace\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Executed Requests during last 5m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgw_response_time_seconds_count{namespace=~\"$namespace\"}[5m])) \n",
     "legendFormat": "Num. of all requests "
    }
   ]
  },
  {
   "title": "PGW Request Rate Per Second Over 5 Minutes",
   "type": "timeseries",
   "description": "Measures the rate of PGW requests per second over a 5-minute window, providing insight into request throughput.",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pgw_response_time_seconds_count{application=\"ServiceManager\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | action: {{action}}]"
    }
   ]
  },
  {
   "title": "PGW Response Time 99th && 95th && 50th Percentile",
   "type": "timeseries",
   "description": "Calculates the 99th && 95th && 50th percentile of PGW response times (in seconds) over a 5-minute window, showing the duration below which 99th && 95th && 50th  of requests are completed, filtered by namespace.",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pgw_response_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (le))",
     "legendFormat": "PGW Response Time 99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pgw_response_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (le))",
     "legendFormat": "PGW Response Time 95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(pgw_response_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (le))",
     "legendFormat": "PGW Response Time 50th Percentile"
    }
   ]
  },
  {
   "title": "PGW Active State Duration",
   "type": "bargauge",
   "description": "Measures the average time PGW remains in an active state over a 5-minute window.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_active{application=\"ServiceManager\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Sum of all PGW Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pgw_errors_total{action!=\"\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of all PGW Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgw_errors_total{action!=\"\"}[$__range]))\n",
     "legendFormat": "Sum of all PGW Errors (Time range)"
    }
   ]
  },
  { "title": "PGW - ADD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Number of Executed ADD Requests during selected time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 135 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pgw_response_time_seconds_count{namespace=~\"$namespace\", action=\"add\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Executed ADD Requests during last 5m",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgw_response_time_seconds_count{namespace=~\"$namespace\", action=\"add\"}[5m])) \n",
     "legendFormat": "Num. of all requests "
    }
   ]
  },
  {
   "title": "PGW ADD Request Rate Per Second Over 5 Minutes",
   "type": "timeseries",
   "description": "Measures the rate of PGW add requests per second over a 5-minute window, providing insight into request throughput.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pgw_response_time_seconds_count{application=\"ServiceManager\", action=\"add\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | action: {{action}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for ADD action, quantile 0.5",
   "type": "timeseries",
   "description": "Provides the average duration of PGW add requests with quantile 0.5 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"add\", quantile=~\"0.5\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for ADD action, quantile 0.99",
   "type": "timeseries",
   "description": "Provides the average duration of PGW add requests with quantile 0.99 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"add\", quantile=~\"0.99\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for ADD action, quantile 0.95",
   "type": "timeseries",
   "description": "Provides the average duration of PGW add requests with quantile 0.99 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"add\", quantile=~\"0.95\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Sum of all PGW ADD Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 155 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pgw_errors_total{action=\"add\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of all PGW ADD Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgw_errors_total{action=\"add\"}[$__range]))\n",
     "legendFormat": "Sum of ADD PGW Errors (Time range)"
    }
   ]
  },
  { "title": "PGW - MODIFY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 } },
  {
   "title": "Number of Executed MODIFY Requests during selected time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 166 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pgw_response_time_seconds_count{namespace=~\"$namespace\", action=\"modify\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Executed MODIFY Requests during last 5m",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgw_response_time_seconds_count{namespace=~\"$namespace\", action=\"modify\"}[5m])) \n",
     "legendFormat": "Num. of all requests "
    }
   ]
  },
  {
   "title": "PGW MODIFY Request Rate Per Second Over 5 Minutes",
   "type": "timeseries",
   "description": "Measures the rate of PGW MODIFY requests per second over a 5-minute window, providing insight into request throughput.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pgw_response_time_seconds_count{application=\"ServiceManager\", service=\"sf-service-manager\", action=\"modify\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | action: {{action}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for MODIFY action, quantile 0.5",
   "type": "timeseries",
   "description": "Provides the average duration of PGW modify requests with quantile 0.5 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"modify\", quantile=~\"0.5\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for MODIFY action, quantile 0.99",
   "type": "timeseries",
   "description": "Provides the average duration of PGW modify requests with quantile 0.99 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"modify\", quantile=~\"0.99\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for MODIFY action, quantile 0.95",
   "type": "timeseries",
   "description": "Provides the average duration of PGW modify requests with quantile 0.95 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"modify\", quantile=~\"0.95\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Sum of all PGW MODIFY Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 186 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pgw_errors_total{action=\"modify\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of all PGW MODIFY Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgw_errors_total{action=\"modify\"}[$__range]))\n",
     "legendFormat": "Sum of ADD PGW Errors (Time range)"
    }
   ]
  },
  { "title": "PGW - DELETE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "Number of Executed DELETE Requests during selected time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 197 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pgw_response_time_seconds_count{namespace=~\"$namespace\", action=\"delete\"}[$__range])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Executed DELETE Requests during last 5m",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgw_response_time_seconds_count{namespace=~\"$namespace\", action=\"delete\"}[5m])) \n",
     "legendFormat": "Num. of all requests "
    }
   ]
  },
  {
   "title": "PGW DELETE Request Rate Per Second Over 5 Minutes",
   "type": "timeseries",
   "description": "Measures the rate of PGW DELETE requests per second over a 5-minute window, providing insight into request throughput.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pgw_response_time_seconds_count{application=\"ServiceManager\", service=\"sf-service-manager\", action=\"delete\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | action: {{action}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for DELETE action, quantile 0.5",
   "type": "timeseries",
   "description": "Provides the average duration of PGW delete requests with quantile 0.5 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"delete\", quantile=~\"0.5\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for DELETE action, quantile 0.99",
   "type": "timeseries",
   "description": "Provides the average duration of PGW delete requests with quantile 0.99 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"delete\", quantile=~\"0.99\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "(Percentile) Average PGW Request Duration for DELETE action, quantile 0.95",
   "type": "timeseries",
   "description": "Provides the average duration of PGW delete requests with quantile 0.95 over the past 5 minutes, reflecting overall performance.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgw_response_time_seconds{application=\"ServiceManager\", action=~\"delete\", quantile=~\"0.95\", service=\"sf-service-manager\", namespace=~\"$namespace\"}[5m])\n* on (namespace, pod) group_left(pod_ip, uid)\nkube_pod_info{namespace=~\"$namespace\"}",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
    }
   ]
  },
  {
   "title": "Sum of all PGW DELETE Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 217 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pgw_errors_total{action=\"delete\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of all PGW DELETE Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgw_errors_total{action=\"delete\"}[$__range]))\n",
     "legendFormat": "Sum of DELETE PGW Errors (Time range)"
    }
   ]
  }
 ]
}