{
 "title": "Service Manager DB",
 "description": "Dashboard for Micrometer instrumented Service Manager (Spring Boot)\n\nFilter by datasource/namespace/node.",
 "tags": [
  "SM",
  "Service Manager",
  "DB"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_memory_used_bytes {namespace=~\"$namespace\"},app)"
   },
   {
    "name": "pod",
    "label": "Podname",
    "query": "label_values({namespace=~\"$namespace\",app=~\"$application\"},kubernetes_pod_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Info",
   "type": "text",
   "description": "Description of dashboard",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Database Performance Dashboard\n\n**Team**: SaaS  \n**Service**: Service Manager (Spring Boot)  \n**Aim**: Monitor database connection pool, Hibernate performance, and cache usage to ensure optimal database interaction and minimize latency.\n\n---\n\n## **Key Metrics**\n- **HikariCP Active Connections**: Active connections in the HikariCP pool.\n- **HikariCP Idle Connections**: Idle connections in the HikariCP pool.\n- **HikariCP Connection Usage**: Percentage of HikariCP pool usage.\n- **Hibernate Open Sessions**: Active Hibernate sessions.\n- **Hibernate Query Execution Time**: Average time to execute Hibernate queries.\n- **Hibernate Cache Hits/Misses**: Cache hit and miss rates.\n\n---\n\n## **Filters**\n- **Namespace**: Narrow down metrics for specific namespace."
   }
  },
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": " Number of SM Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Metrics Hikari-Pool-1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average HikariPool-1 Active Connections",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n\n    )\n  )[${__range}:]\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HikariPool-1 Active Connections",
     "type": "timeseries",
     "description": "The average number of active connections in the HikariCP connection pool.",
     "gridPos": { "h": 10, "w": 9, "x": 3, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n\n    )\n  )[${__range}:]\n)",
       "legendFormat": "Average number of active connections HikariPool-1 (time range)"
      }
     ]
    },
    {
     "title": "Total num. of active HikariPool-1 conn. last 5 min.",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)",
       "legendFormat": "Average of total number of active HikariPool-1 connection (time range)"
      }
     ]
    },
    {
     "title": "Ave. num.of pending connections HikariPool-1",
     "type": "stat",
     "gridPos": { "h": 11, "w": 3, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\"}[${__range}])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ave. num. of pending connections HikariPool-1",
     "type": "timeseries",
     "description": "requests waiting for a connection",
     "gridPos": { "h": 11, "w": 9, "x": 3, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\", pool=~\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg(\n  avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\"}[${__range}])\n)\n",
       "legendFormat": "Ave. num. of pending connections HikariPool-1 (time range)"
      }
     ]
    },
    {
     "title": "Ave. num. of idle connections in the HikariPool-1",
     "type": "stat",
     "gridPos": { "h": 11, "w": 3, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ave. num. of idle connections in the HikariPool-1",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
       "legendFormat": "Average number of idle connections in the HikariPool-1 (time range)"
      }
     ]
    },
    {
     "title": "Ave. time to create a new connection in the HikarPool-1",
     "type": "timeseries",
     "description": "The average time (in seconds) spent waiting to new connection from the HikariPool-1 pool.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_creation_seconds_sum{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=~\"HikariPool-1\"}[5m]) \n/ \navg_over_time(hikaricp_connections_creation_seconds_count{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=~\"HikariPool-1\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_creation_seconds_sum{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=\"HikariPool-1\"}[5m])\n    )\n  )[${__range}:]\n)\n/\navg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_creation_seconds_count{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=\"HikariPool-1\"}[5m])\n    )\n  )[${__range}:]\n)\n",
       "legendFormat": "Ave. time to create a new connection in the HikarPool-1 (time range)"
      }
     ]
    },
    {
     "title": "HikariPool-1 Connection Wait Time",
     "type": "timeseries",
     "description": "The average time (in seconds) spent waiting to acquire a connection from the HikariPool-1 pool.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_acquire_seconds_sum{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=~\"HikariPool-1\"}[5m]) \n/ \navg_over_time(hikaricp_connections_acquire_seconds_count{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=~\"HikariPool-1\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_acquire_seconds_sum{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=\"HikariPool-1\"}[5m])\n    )\n  )[${__range}:]\n)\n/\navg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_acquire_seconds_count{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=\"HikariPool-1\"}[5m])\n    )\n  )[${__range}:]\n)\n",
       "legendFormat": "Average HikariPool-1 Connection Wait Time (time range)"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Metrics Hikari-Pool-2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average HikariPool-1 Active Connections",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-1\", kubernetes_pod_name=~\"$pod\"}[1m])\n\n    )\n  )[${__range}:]\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HikariPool-2 Active Connections",
     "type": "timeseries",
     "description": "The average number of active connections in the HikariCP connection pool.",
     "gridPos": { "h": 10, "w": 9, "x": 3, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n\n    )\n  )[${__range}:]\n)",
       "legendFormat": "Average number of active connections HikariPool-2 (time range)"
      }
     ]
    },
    {
     "title": "Total num. of active HikariPool-2 conn. last 5 min.",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      increase(hikaricp_connections_active{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[5m])\n    )\n  )[${__range}:]\n)",
       "legendFormat": "Average of total number of active HikariPool-2 connection (time range)"
      }
     ]
    },
    {
     "title": "Ave. num.of pending connections HikariPool-2",
     "type": "stat",
     "gridPos": { "h": 11, "w": 3, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\",}[${__range}])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ave. num. of pending connections HikariPool-2",
     "type": "timeseries",
     "description": "requests waiting for a connection",
     "gridPos": { "h": 11, "w": 9, "x": 3, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\", pool=~\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg(\n  avg_over_time(hikaricp_connections_pending{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\"}[${__range}])\n)\n",
       "legendFormat": "Ave. num. of pending connections HikariPool-2 (time range)"
      }
     ]
    },
    {
     "title": "Ave. num. of idle connections in the HikariPool-2",
     "type": "stat",
     "gridPos": { "h": 11, "w": 3, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ave. num. of idle connections in the HikariPool-2",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_idle{namespace=~\"$namespace\", app=~\"$application\", pool=\"HikariPool-2\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n  )[${__range}:]\n)",
       "legendFormat": "Average number of idle connections in the HikariPool-2 (time range)"
      }
     ]
    },
    {
     "title": "Ave. time to create a new connection in the HikarPool-2",
     "type": "timeseries",
     "description": "The average time (in seconds) spent waiting to new connection from the HikariPool-2 pool.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_creation_seconds_sum{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=~\"HikariPool-2\"}[5m]) \n/ \navg_over_time(hikaricp_connections_creation_seconds_count{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=~\"HikariPool-2\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_creation_seconds_sum{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=\"HikariPool-2\"}[5m])\n    )\n  )[${__range}:]\n)\n/\navg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_creation_seconds_count{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=\"HikariPool-2\"}[5m])\n    )\n  )[${__range}:]\n)\n",
       "legendFormat": "Ave. time to create a new connection in the HikarPool-2 (time range)"
      }
     ]
    },
    {
     "title": "HikariPool-2 Connection Wait Time",
     "type": "timeseries",
     "description": "The average time (in seconds) spent waiting to acquire a connection from the HikariPool-2 pool.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(hikaricp_connections_acquire_seconds_sum{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=~\"HikariPool-2\"}[5m]) \n/ \navg_over_time(hikaricp_connections_acquire_seconds_count{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=~\"HikariPool-2\"}[5m])\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
       "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}}]"
      },
      {
       "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_acquire_seconds_sum{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=\"HikariPool-2\"}[5m])\n    )\n  )[${__range}:]\n)\n/\navg_over_time(\n  (\n    avg(\n      avg_over_time(hikaricp_connections_acquire_seconds_count{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", pool=\"HikariPool-2\"}[5m])\n    )\n  )[${__range}:]\n)\n",
       "legendFormat": "Average HikariPool-2 Connection Wait Time (time range)"
      }
     ]
    }
   ]
  },
  {
   "title": "Hibernate metrics - entityManagerFactory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Open Sessions - entityManagerFactory",
   "type": "timeseries",
   "description": "The current number of open Hibernate sessions.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_sessions_open_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hibernate_sessions_open_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "Average Open Sessions - entityManagerFactory (time range)"
    }
   ]
  },
  {
   "title": "Closed Sessions - entityManagerFactory",
   "type": "timeseries",
   "description": "The total number of Hibernate sessions closed since application startup.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_sessions_closed_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hibernate_sessions_closed_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "Closed Sessions - entityManagerFactory (time range)"
    }
   ]
  },
  {
   "title": "Entity Inserts - entityManagerFactory",
   "type": "timeseries",
   "description": "The total number of entity insert operations in Hibernate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(hibernate_entities_updates_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}[5m])\n\n\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Entity Updates - entityManagerFactory",
   "type": "timeseries",
   "description": "The total number of entity update operations in Hibernate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_updates_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Entity Deletes - entityManagerFactory",
   "type": "timeseries",
   "description": "The total number of entity delete operations in Hibernate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_deletes_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Query Execution Count - entityManagerFactory",
   "type": "timeseries",
   "description": "The total number of SQL queries executed by Hibernate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_query_executions_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Cache Hit Count - entityManagerFactory",
   "type": "timeseries",
   "description": "The total number of cache hits in Hibernate (2nd level cache).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_loads_total{namespace=~\"$namespace\", entityManagerFactory=\"entityManagerFactory\"}  \n* on (namespace, pod, container) group_left(uid)  \nkube_pod_container_info{namespace=~\"$namespace\"}  \n* on (namespace, pod) group_left(pod_ip)  \nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Cache Miss Count - entityManagerFactory",
   "type": "timeseries",
   "description": "The total number of cache misses when reading from the Hibernate second-level cache.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_fetches_total{namespace=~\"$namespace\", entityManagerFactory=\"entityManagerFactory\"}  \n* on (namespace, pod, container) group_left(uid)  \nkube_pod_container_info{namespace=~\"$namespace\"}  \n* on (namespace, pod) group_left(pod_ip)  \nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Put Count - entityManagerFactory",
   "type": "timeseries",
   "description": "The number of cache write operations in Hibernate (2nd level cache).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_inserts_total{namespace=~\"$namespace\", entityManagerFactory=\"entityManagerFactory\"}  \n* on (namespace, pod, container) group_left(uid)  \nkube_pod_container_info{namespace=~\"$namespace\"}  \n* on (namespace, pod) group_left(pod_ip)  \nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Cache Eviction Count - entityManagerFactory",
   "type": "timeseries",
   "description": "The total number of cache eviction operations in Hibernate (2nd level cache).\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_collections_recreates_total{namespace=~\"$namespace\", entityManagerFactory=\"entityManagerFactory\"}  \n* on (namespace, pod, container) group_left(uid)  \nkube_pod_container_info{namespace=~\"$namespace\"}  \n* on (namespace, pod) group_left(pod_ip)  \nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Average Query Execution Time - entityManagerFactory",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hibernate_query_executions_max_seconds{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Query Execution Time - entityManagerFactory",
   "type": "timeseries",
   "description": "The average time of SQL query execution by Hibernate.",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(hibernate_query_executions_max_seconds{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}[5m])\n* on (namespace, pod) group_left(uid, pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hibernate_query_executions_max_seconds{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"entityManagerFactory\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "Average Query Execution Time - entityManagerFactory (time range)"
    }
   ]
  },
  { "title": "Hibernate metrics - monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Open Sessions - monitoring",
   "type": "timeseries",
   "description": "The current number of open Hibernate sessions.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_sessions_open_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hibernate_sessions_open_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "Average Open Sessions - monitoring (time range)"
    }
   ]
  },
  {
   "title": "Closed Sessions - monitoring",
   "type": "timeseries",
   "description": "The total number of Hibernate sessions closed since application startup.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_sessions_closed_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hibernate_sessions_closed_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "Closed Sessions - monitoring (time range)"
    }
   ]
  },
  {
   "title": "Entity Inserts - monitoring",
   "type": "timeseries",
   "description": "The total number of entity insert operations in Hibernate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(hibernate_entities_updates_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}[5m])\n\n\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Entity Updates - monitoring",
   "type": "timeseries",
   "description": "The total number of entity update operations in Hibernate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_updates_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Entity Deletes - monitoring",
   "type": "timeseries",
   "description": "The total number of entity delete operations in Hibernate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_deletes_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Query Execution Count - monitoring",
   "type": "timeseries",
   "description": "The total number of SQL queries executed by Hibernate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_query_executions_total{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}\n* on (namespace, pod, container) group_left(uid)\nkube_pod_container_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n* on (namespace, pod) group_left(pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Cache Hit Count - monitoring",
   "type": "timeseries",
   "description": "The total number of cache hits in Hibernate (2nd level cache).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_loads_total{namespace=~\"$namespace\", entityManagerFactory=\"monitoring\"}  \n* on (namespace, pod, container) group_left(uid)  \nkube_pod_container_info{namespace=~\"$namespace\"}  \n* on (namespace, pod) group_left(pod_ip)  \nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Cache Miss Count - monitoring",
   "type": "timeseries",
   "description": "The total number of cache misses when reading from the Hibernate second-level cache.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_fetches_total{namespace=~\"$namespace\", entityManagerFactory=\"monitoring\"}  \n* on (namespace, pod, container) group_left(uid)  \nkube_pod_container_info{namespace=~\"$namespace\"}  \n* on (namespace, pod) group_left(pod_ip)  \nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Put Count - monitoring",
   "type": "timeseries",
   "description": "The number of cache write operations in Hibernate (2nd level cache).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_entities_inserts_total{namespace=~\"$namespace\", entityManagerFactory=\"monitoring\"}  \n* on (namespace, pod, container) group_left(uid)  \nkube_pod_container_info{namespace=~\"$namespace\"}  \n* on (namespace, pod) group_left(pod_ip)  \nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Cache Eviction Count - monitoring",
   "type": "timeseries",
   "description": "The total number of cache eviction operations in Hibernate (2nd level cache).\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hibernate_collections_recreates_total{namespace=~\"$namespace\", entityManagerFactory=\"monitoring\"}  \n* on (namespace, pod, container) group_left(uid)  \nkube_pod_container_info{namespace=~\"$namespace\"}  \n* on (namespace, pod) group_left(pod_ip)  \nkube_pod_info{namespace=~\"$namespace\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    }
   ]
  },
  {
   "title": "Average Query Execution Time - monitoring",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hibernate_query_executions_max_seconds{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Query Execution Time - monitoring",
   "type": "timeseries",
   "description": "The average time of SQL query execution by Hibernate.",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(hibernate_query_executions_max_seconds{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}[5m])\n* on (namespace, pod) group_left(uid, pod_ip)\nkube_pod_info{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\"}\n",
     "legendFormat": "[sm-pod-ip: {{pod_ip}} | sm-pod-id: {{uid}} | entityManagerFactory: {{entityManagerFactory}}]"
    },
    {
     "expr": "avg_over_time(\n  (\n    avg(\n      avg_over_time(hibernate_query_executions_max_seconds{namespace=~\"$namespace\", pod=~\"sf-service-manager-.*\", entityManagerFactory=\"monitoring\"}[5m])\n    )\n  )[${__range}:]\n)\n",
     "legendFormat": "Average Query Execution Time - entityManagerFactory (time range)"
    }
   ]
  }
 ]
}