---
# Supported annotations
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/
apiVersion: v1
kind: Service
metadata:
  name: nodejs-application-alb
  namespace: lbc-app-alb
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
  selector:
    app: nodejs-application-alb