---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-test
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "configmaps", "secrets", "services", "pods", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-test-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-test
subjects:
  - kind: Group
    name: dev-test
    apiGroup: rbac.authorization.k8s.io